name: Update Scholar Stats

on:
  schedule:
    - cron: '0 0 */2 * *'  # 每2天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-scholar-stats:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # 延长到5分钟
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        path: main
    
    - name: Checkout google-scholar-stats branch  
      uses: actions/checkout@v4
      with:
        ref: google-scholar-stats
        path: google-scholar-stats
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd main/.github/google_scholar_crawler
        pip install -r requirements.txt
    
    - name: Update scholar data
      timeout-minutes: 3  # 脚本执行3分钟超时
      env:
        SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
      run: |
        cd main/.github/google_scholar_crawler
        python main.py
        # 复制结果到google-scholar-stats分支
        cp -r results/* ../../google-scholar-stats/results/
    
    - name: Commit and push results
      run: |
        cd google-scholar-stats
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add results/*.json
        git commit -m "Update Scholar Stats $(date '+%Y-%m-%d')" || exit 0
        git push